wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.4
    t:
      1:
      - 1
      - 9
      2:
      - 1
      - 9
      4: 3.9.4
      5: 0.10.30
      8:
      - 3
      - 5
